### PR TITLE
kton balance fixed

### PR DESCRIPTION
**Pull request by isunaslabs**
-Fixed the issue where CKTON balance wasn't showing the other CKTONs that were migrated from Crab 1.0 account.

### CODE REVIEW

**Comment by isunaslabs** [comment]
Please help reviewing this build. For testing you can append `?network=Crab&account=0x1FE43f304CA8F1D99f79f7EC71DE9b7e329B91bD` on the URL for testing

**Comment by 1022ranji** [comment]
https://staking-529ct43bi-itering.vercel.app/#/staking?network=Crab&account=0xE45FD7BEf2736Dad2d5620052cA37A9603376aeA
这个账户0xE45FD7BEf2736Dad2d5620052cA37A9603376aeA，MetaMask 中有1.64CKTON，但是在上面的测试链接中显示的是负数，-419CKTON
image
image

**Comment by isunaslabs** [comment]
It's weird, I'm checking it now

**Comment by isunaslabs** [comment]
@1022ranji the problem is completely resolved

**Review by wuminzhe — APPROVED** [review]

**Review by 1022ranji — APPROVED** [review]

**Pull request merged**
