### PR TITLE
Support Koi Testnet

### PR DESCRIPTION
**Pull request by JayJay1024**

### CODE REVIEW

**Comment by hackfisher** [comment]
https://docs.darwinia.network/build/getting-started/networks/pangolin/

Pangolin has been removed, please support Koi instead.

**Comment by JayJay1024** [comment]
> https://docs.darwinia.network/build/getting-started/networks/pangolin/
> 
> Pangolin has been removed, please support Koi instead.

Done

**Comment by hackfisher** [comment]
subql is not working for Koi? 

network issues for
https://subql.darwinia.network/subql-apps-pangolin/

**Comment by JayJay1024** [comment]
> subql is not working for Koi?

Yeah, subql is only used in _Latest Staking Rewards_. I'll see if I can deploy one later if necessary.

**Review by 1022ranji — APPROVED** [review]

**Pull request merged**
