### PR TITLE
ux improvement

### PR DESCRIPTION
**Pull request by isunaslabs**
improved error reporting messages

### CODE REVIEW

**Comment by isunaslabs** [comment]
@wuminzhe and @1022ranji  please help me reviewing this PR. It simply just improved error reporting for the user.

**Review by 1022ranji — APPROVED** [review]

**Comment by fewensa** [comment]
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xEB7e82A67CDFA3E742e0f3315Fd4EEd7B05730CC","to":"0x0000000000000000000000000000000000000401","data":"0x0d0078710e3125ff0e791133895f5b32aae077208026bf1625de73529e3b6685684200","accessList":null}, error={"code":4901}, code=CALL_EXCEPTION, version=providers/5.7.2)
    makeError https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:169
    throwError https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:169
    checkError$2 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    perform https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    g https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    promise callback*$ https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    5 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    5 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    perform https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    _call https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    _call https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    call https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    b https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    promise callback*$ https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    b https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    promise callback*$ https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    call https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    dryRun https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:209
    doDispatch https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:209
    dispatch https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:209
    setKeysH https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:209
    o https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:239
    o6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:271
    Nb$2 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    Tb$2 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    Ub$1 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    nf https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    se https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    2 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    Rk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Jb$2 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    hd$2 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    fd$2 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    ed$1 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    pf https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    qf https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    sf https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    sf https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    Fj https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Tk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Vk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Uk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Jk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Hk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    g6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17
    C6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17
    EventHandlerNonNull* https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17
    <anonymous> https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17
index.4dbaa51f.js:239:13337

```

**Comment by fewensa** [comment]
```
Error: Network not supported
    et moz-extension://b90a37b4-d242-4888-bfd4-aa60c9e7d007/page.js:1
    handleResponse moz-extension://b90a37b4-d242-4888-bfd4-aa60c9e7d007/page.js:1
    <anonymous> moz-extension://b90a37b4-d242-4888-bfd4-aa60c9e7d007/page.js:1
    EventListener.handleEvent* moz-extension://b90a37b4-d242-4888-bfd4-aa60c9e7d007/page.js:1
    <anonymous> moz-extension://b90a37b4-d242-4888-bfd4-aa60c9e7d007/page.js:1
    <anonymous> moz-extension://b90a37b4-d242-4888-bfd4-aa60c9e7d007/page.js:1
page.js:1:62053
    o moz-extension://b90a37b4-d242-4888-bfd4-aa60c9e7d007/page.js:1
    buildEip1193Fetcher https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    send https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    perform https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    5 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    5 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:179
    .....
    sf https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    sf https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:29
    Fj https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Tk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Vk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Uk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Jk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    Hk https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:32
    g6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17
    C6 https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17
    (Async: EventHandlerNonNull)
    <anonymous> https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17
    <anonymous> https://staking-6wiyeaieq-itering.vercel.app/assets/index.4dbaa51f.js:17

```

**Comment by isunaslabs** [comment]
@wuminzhe I think this error is actually the chain issue. @1022ranji do you think I should merge this PR to the main branch?

**Comment by 1022ranji** [comment]
yes, please merge it.

**Pull request merged**
