### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by isunaslabs**
-power is dynamic
-reserved in staking is dynamic

### CODE REVIEW

**Comment by isunaslabs** [comment]
@1022ranji @wuminzhe  please test this PR

**Comment by isunaslabs** [comment]
@1022ranji Please continue testing the staking functionality from the final build. Thanks for your time

**Comment by isunaslabs** [comment]
@1022ranji Please go ahead and test the deposit functionality, etc

**Comment by isunaslabs** [comment]
@1022ranji Please help me testing the last code build, I fixed all the bugs that were listed in Notion.

**Comment by isunaslabs** [comment]
@1022ranji please help me reviewing the last built code. It has fixed all the issues you noted on Notion.

**Comment by isunaslabs** [comment]
Hi @1022ranji , please check the last code build, it contains Pangoro environment ready for testing

**Review by wuminzhe — APPROVED** [review]

**Review by hackfisher — APPROVED** [review]
LGTM, suggest to merge first for public preview and test, for existing bugs, we can file separate PR to resolve them.

**Pull request merged**
